# Generated by Django 2.2.4 on 2019-11-26 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='users/default.png', upload_to='users')),
                ('sex', models.CharField(choices=[('M', 'Муж'), ('F', 'Жен')], default='1', max_length=1)),
                ('photobg', models.ImageField(blank=True, null=True, upload_to='users/bg')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('accepter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link2', to='Profile.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link1', to='Profile.Profile')),
            ],
        ),
    ]
