# Generated by Django 2.2.4 on 2019-12-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended', models.DateTimeField(auto_now_add=True)),
                ('FromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='Profile.Profile')),
                ('ToUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='Profile.Profile')),
            ],
        ),
    ]
