# Generated by Django 2.2.4 on 2019-12-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sended',
        ),
    ]
