# Generated by Django 2.2.4 on 2019-12-01 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_messages_sended'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sended',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
