# Generated by Django 2.2.4 on 2019-12-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20191130_1557'),
        ('Profile', '0006_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Film'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='serial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Serial'),
        ),
    ]
