# Generated by Django 2.2.4 on 2019-11-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0002_genrelist_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('action', models.TextField()),
                ('typeAction', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
                ('userlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.UserList')),
                ('userlistF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.UserListF')),
            ],
        ),
    ]
