# Generated by Django 2.2.4 on 2019-11-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='action',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
