# Generated by Django 2.2.4 on 2019-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0002_userfeed_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='action',
            field=models.TextField(),
        ),
    ]
