# Generated by Django 2.2.4 on 2019-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_auto_20191111_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeed',
            name='typeAction',
            field=models.TextField(blank=True),
        ),
    ]
