# Generated by Django 2.2.4 on 2019-11-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0004_userfeed_typeaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='typeAction',
            field=models.TextField(null=True),
        ),
    ]
