# Generated by Django 2.2.7 on 2019-11-16 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0007_userfeed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile'),
        ),
    ]
