# Generated by Django 2.2.7 on 2019-11-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0008_auto_20191116_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeed',
            name='lastaction',
        ),
    ]
