# Generated by Django 2.2.4 on 2019-11-26 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinopoiskid', models.IntegerField()),
                ('name', models.TextField()),
                ('originalname', models.TextField()),
                ('year', models.IntegerField()),
                ('length', models.IntegerField()),
                ('disctiption', models.TextField(default='Нет данных')),
            ],
        ),
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Posters')),
                ('movie', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('episodecount', models.IntegerField()),
                ('disctiption', models.TextField(default='Нет данных')),
                ('rating', models.FloatField(default=0)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Movie')),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.Posters')),
            ],
        ),
        migrations.CreateModel(
            name='StatusList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserListS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrate', models.IntegerField(default=0)),
                ('userstatus', models.IntegerField(default=1)),
                ('countreview', models.IntegerField(default=0)),
                ('userepisode', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Movie')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserListF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrate', models.IntegerField(default=0)),
                ('userstatus', models.IntegerField(default=1)),
                ('countreview', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.Movie')),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.Posters')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.StatusList'),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.StatusList'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.GenreList')),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.Movie')),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.Posters')),
            ],
        ),
    ]
