# Generated by Django 2.2.4 on 2019-11-04 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('originalname', models.TextField()),
                ('length', models.IntegerField()),
                ('year', models.IntegerField()),
                ('kinopoiskid', models.IntegerField()),
                ('img', models.URLField(default='https://dummyimage.com/210x300/546de5/fff.png&text=Poster%20Not%20Found')),
                ('rating', models.FloatField(default=0)),
                ('disctiption', models.TextField(default='Нет данных')),
            ],
        ),
        migrations.CreateModel(
            name='GenreList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('episodecount', models.IntegerField()),
                ('disctiption', models.TextField(default='Нет данных')),
                ('img', models.ImageField(default='default.png', upload_to='Seasons')),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('originalname', models.TextField()),
                ('episodelength', models.IntegerField()),
                ('year', models.IntegerField()),
                ('kinopoiskid', models.IntegerField()),
                ('img', models.URLField(default='https://dummyimage.com/210x300/546de5/fff.png&text=Poster%20Not%20Found')),
            ],
        ),
        migrations.CreateModel(
            name='StatusList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserListF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrate', models.IntegerField(default=0)),
                ('userstatus', models.IntegerField(default=1)),
                ('countreview', models.IntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrate', models.IntegerField(default=0)),
                ('userstatus', models.IntegerField(default=1)),
                ('userepisode', models.IntegerField(default=0)),
                ('countreview', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Season')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Serial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Serial'),
        ),
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.StatusList'),
        ),
        migrations.CreateModel(
            name='GenreF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Film')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.GenreList')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.GenreList')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Serial')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.StatusList'),
        ),
    ]
