# Generated by Django 2.2.4 on 2019-11-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='movie',
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Series'),
        ),
    ]
