# Generated by Django 2.2.4 on 2019-11-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genrelist',
            name='tag',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
