# Generated by Django 2.2.4 on 2019-10-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20191017_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photobg',
            field=models.ImageField(blank=True, upload_to='users/bg'),
        ),
    ]
