# Generated by Django 2.2.4 on 2019-10-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_photobg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photobg',
            field=models.ImageField(blank=True, null=True, upload_to='users/bg'),
        ),
    ]
