# Generated by Django 2.2.4 on 2019-10-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20191017_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Муж'), ('F', 'Жен')], default='1', max_length=1),
        ),
    ]
