# Generated by Django 2.2.4 on 2019-10-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20191017_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frendlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('link1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link1', to='Profile.Profile')),
                ('link2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link2', to='Profile.Profile')),
            ],
        ),
    ]
