# Generated by Django 2.2.4 on 2019-10-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_frendlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frendlist',
            new_name='Friendlist',
        ),
    ]
