# Generated by Django 2.2.4 on 2019-10-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20191017_2301'),
    ]

    operations = [
    ]
