# Generated by Django 2.2.4 on 2019-10-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_profile_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cropping',
        ),
    ]
