# Generated by Django 2.2.4 on 2019-10-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_remove_profile_cropping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='link2',
            new_name='accepter',
        ),
        migrations.RenameField(
            model_name='friendlist',
            old_name='link1',
            new_name='sender',
        ),
    ]
