# Generated by Django 2.2.4 on 2019-10-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_auto_20191029_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='accepter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link2', to='Profile.Profile'),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link1', to='Profile.Profile'),
        ),
    ]
