UserStat={
    "planned":{
        "id":1,
        "name":"В планах",
    },
    "watch":{
        "id":2,
        "name":"Смотрю",
    },
    "watched":{
        "id":3,
        "name":"Просмотрено",
    },
    "rewatch":{
        "id":4,
        "name":"Пересматриваю",
    },
    "drop":{
        "id":5,
        "name":"Брошено",
    }
}