# Generated by Django 3.0.2 on 2020-01-26 18:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20191207_2344'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='friendlist',
            managers=[
                ('friends', django.db.models.manager.Manager()),
            ],
        ),
    ]
