# Generated by Django 3.0.4 on 2020-04-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Profile', '0010_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Feed',
        ),
    ]
