# Generated by Django 3.0.4 on 2020-04-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_auto_20200407_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fillowing',
            new_name='following',
        ),
    ]
