# Generated by Django 2.2 on 2019-07-23 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='name',
        ),
    ]
