# Generated by Django 2.2 on 2019-07-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_serial_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='originalname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
