# Generated by Django 2.2 on 2019-07-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_serial_originalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='episodelength',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
