# Generated by Django 2.2 on 2019-07-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_serial_episodelength'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='date',
            field=models.DateField(default="1999-12-31"),
            preserve_default=False,
        ),
    ]
