# Generated by Django 2.2 on 2019-07-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_serial_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Serialid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Serial')),
            ],
        ),
    ]
