# Generated by Django 2.2 on 2019-07-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='Serialid',
            new_name='Serial',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='Genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Main.GenreList'),
            preserve_default=False,
        ),
    ]
