# Generated by Django 2.2 on 2019-07-24 01:51

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20190724_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='serial',
            name='status',
            field=models.IntegerField(default=0, verbose_name=Main.models.StatusList),
            preserve_default=False,
        ),
    ]
