# Generated by Django 2.2 on 2019-07-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20190724_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslist',
            name='color',
            field=models.TextField(default='#000'),
            preserve_default=False,
        ),
    ]
