# Generated by Django 2.2 on 2019-07-24 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_statuslist_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.StatusList'),
        ),
    ]
