# Generated by Django 2.2 on 2019-07-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20190724_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='Serial',
            new_name='serial',
        ),
    ]
