# Generated by Django 2.2 on 2019-07-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_ratinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.RatingList'),
        ),
    ]
