# Generated by Django 2.2 on 2019-07-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_auto_20190725_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='countreview',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlist',
            name='userstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.UserStatus'),
            preserve_default=False,
        ),
    ]
