# Generated by Django 2.2 on 2019-07-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_auto_20190725_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='serial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.Serial'),
            preserve_default=False,
        ),
    ]
