# Generated by Django 2.2 on 2019-08-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_auto_20190728_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='countreview',
        ),
        migrations.AddField(
            model_name='serial',
            name='countreview',
            field=models.IntegerField(default=0),
        ),
    ]
