# Generated by Django 2.2 on 2019-08-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_auto_20190801_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='disctiption',
            field=models.TextField(default='Нет данных'),
        ),
    ]
