# Generated by Django 2.2 on 2019-08-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_season_disctiption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='num',
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
