# Generated by Django 2.2 on 2019-08-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_auto_20190804_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='countreview',
        ),
        migrations.AddField(
            model_name='userlist',
            name='countreview',
            field=models.IntegerField(default=0),
        ),
    ]
