# Generated by Django 2.2 on 2019-08-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_auto_20190804_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='date',
        ),
        migrations.AddField(
            model_name='season',
            name='date',
            field=models.DateField(default='1999-11-11'),
            preserve_default=False,
        ),
    ]
