# Generated by Django 2.2.4 on 2019-09-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_remove_serial_disctiption'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='year',
            field=models.IntegerField(default=1900, max_length=4),
            preserve_default=False,
        ),
    ]
