# Generated by Django 2.2.4 on 2019-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_serial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='img',
            field=models.ImageField(default='https://dummyimage.com/210x300/546de5/fff.png&text=Poster Not Found', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serial',
            name='kinopoiskid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serial',
            name='year',
            field=models.IntegerField(),
        ),
    ]
