# Generated by Django 2.2.4 on 2019-09-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_auto_20190915_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='img',
            field=models.URLField(default='https://dummyimage.com/210x300/546de5/fff.png&text=Poster%20Not%20Found'),
        ),
    ]
