# Generated by Django 2.2.4 on 2019-09-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20190915_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
