# Generated by Django 2.2.4 on 2019-09-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0033_auto_20190923_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='rating',
        ),
        migrations.DeleteModel(
            name='RatingList',
        ),
    ]
