# Generated by Django 2.2.4 on 2019-09-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_auto_20190924_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='img',
            field=models.URLField(default='https://dummyimage.com/210x300/546de5/fff.png&text=Poster%20Not%20Found'),
        ),
    ]
