# Generated by Django 2.2.4 on 2019-09-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0036_serieslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='date',
        ),
    ]
