# Generated by Django 2.2.4 on 2019-10-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0037_remove_season_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='img',
            field=models.ImageField(default='default.png', upload_to='Seasons'),
        ),
    ]
