# Generated by Django 2.2.4 on 2019-10-10 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0038_auto_20191002_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('originalname', models.TextField()),
                ('length', models.IntegerField()),
                ('year', models.IntegerField()),
                ('kinopoiskid', models.IntegerField()),
                ('img', models.URLField(default='https://dummyimage.com/210x300/546de5/fff.png&text=Poster%20Not%20Found')),
                ('rating', models.FloatField(default=0)),
                ('disctiption', models.TextField(default='Нет данных')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Main.StatusList')),
            ],
        ),
        migrations.CreateModel(
            name='UserListF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrate', models.IntegerField(default=0)),
                ('userstatus', models.IntegerField(default=1)),
                ('countreview', models.IntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenreF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Film')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.GenreList')),
            ],
        ),
    ]
