# Generated by Django 2.2.4 on 2019-10-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0039_film_genref_userlistf'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
