# Generated by Django 2.2.4 on 2019-10-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0040_film_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
    ]
