# Generated by Django 3.0.2 on 2020-01-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200127_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userlistf',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
