# Generated by Django 3.0.2 on 2020-01-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200128_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
