# Generated by Django 3.0.2 on 2020-02-28 19:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20200129_0930'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='freezing',
            field=models.BooleanField(default=False),
        ),
    ]
