# Generated by Django 3.0.2 on 2020-02-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20200228_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='freezing',
        ),
    ]
