# Generated by Django 3.0.5 on 2020-04-10 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('originalname', models.TextField()),
                ('length', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('kinopoiskid', models.PositiveIntegerField(null=True)),
                ('disctiption', models.TextField(null=True)),
                ('rating', models.FloatField(default=0, editable=False)),
                ('series', models.BooleanField(default=False)),
                ('img', models.ImageField(default='default.png', upload_to='Posters')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('name',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('episodecount', models.IntegerField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('img', models.ImageField(default='default.png', upload_to='Posters')),
                ('rating', models.FloatField(default=0, editable=False)),
                ('disctiption', models.TextField(default='Нет данных')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='MyWatchList.Movie')),
            ],
            options={
                'ordering': ('movie__name', 'position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StatusList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userrate', models.PositiveSmallIntegerField(default=0)),
                ('userstatus', models.PositiveSmallIntegerField(default=1)),
                ('rewatch', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userepisode', models.PositiveIntegerField(default=0, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWatchList.Movie')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyWatchList.Season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SeriesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serieslist', to='MyWatchList.Season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MyWatchList.StatusList'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('spoiler', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
    ]
