# Generated by Django 3.0.5 on 2020-04-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdbid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
