# Generated by Django 3.0.3 on 2020-03-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='disctiption',
        ),
        migrations.RemoveField(
            model_name='serial',
            name='disctiption',
        ),
        migrations.AddField(
            model_name='movie',
            name='disctiption',
            field=models.TextField(default='Нет данных'),
        ),
    ]
