# Generated by Django 3.0.5 on 2020-04-11 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0003_auto_20200411_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 3, 27, 46, 828089)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_dateRU',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 3, 27, 46, 829088)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdbid',
            field=models.CharField(max_length=100),
        ),
    ]
