# Generated by Django 3.0.3 on 2020-03-13 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0003_auto_20200313_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='movie',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('movie__name', 'position', 'name')},
        ),
        migrations.RemoveField(
            model_name='season',
            name='serial',
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serial', to='MyWatchList.Movie'),
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Serial',
        ),
    ]
