# Generated by Django 3.0.4 on 2020-03-26 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('MyWatchList', '0005_auto_20200316_0817'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='commentmodel',
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='watchlist',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='movie',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='content_type',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='MyWatchList.Movie'),
        ),
        migrations.AlterField(
            model_name='serieslist',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serieslist', to='MyWatchList.Season'),
        ),
    ]
