# Generated by Django 3.0.5 on 2020-04-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0005_auto_20200411_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='kinopoiskid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
