# Generated by Django 3.0.4 on 2020-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0006_auto_20200326_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='disctiption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
