# Generated by Django 3.0.5 on 2020-04-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0008_auto_20200411_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
