# Generated by Django 3.0.5 on 2020-04-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0010_season_tmdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='serieslist',
            name='disctiption',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='serieslist',
            name='tmdbid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
