# Generated by Django 3.0.5 on 2020-04-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0011_auto_20200411_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
