# Generated by Django 3.0.5 on 2020-04-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0012_auto_20200411_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serieslist',
            name='tmdbid',
        ),
        migrations.AlterField(
            model_name='serieslist',
            name='disctiption',
            field=models.TextField(blank=True, default='Нет данных', null=True),
        ),
    ]
