# Generated by Django 3.0.7 on 2020-08-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0015_replymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replymodel',
            old_name='comment',
            new_name='item',
        ),
    ]
