# Generated by Django 3.2.7 on 2021-09-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWatchList', '0016_auto_20200817_2203'),
        ('MyWatchList', '0018_auto_20210901_0206'),
    ]

    operations = [
    ]
